#ifndef PDS_TIMEOUT_CONSTANTS
#define PDS_TIMEOUT_CONSTANTS

#define EB_TIMEOUT 2
#define EB_TIMEOUT_SLOW 120

#define EB_TIMEOUT_MS EB_TIMEOUT * 1000
#define EB_TIMEOUT_SLOW_MS EB_TIMEOUT_SLOW * 1000

#endif
